=== pablogalvezprojectosdaw/XMLRepo/clientes/clientesSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sede">
                    <xs:simpleType>
                        <xs:attribute name = "codigo"/>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element type="xs:string" name="direccion" />
                                    <xs:element type="xs:string" name="empleado"/>
                                    <xs:element type="xs:date" name="fecha"/>
                                    <xs:element type="xs:string" name="descripcion"/>
                                    <xs:element name="cliente">
                                        <xs:simpleType>
                                            <xs:attribute name = "codigo"/>
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element type="xs:string" name="direccion" />
                                                        <xs:element type="xs:byte" name="numeroviviendas"/>
                                                        <xs:element type="xs:short" name="coste"/>
                                                        <xs:element type="xs:string" name="resumen"/>
                                                        <xs:element type="xs:date" name="plazo"/>
                                                    </xs:sequence>
                                            </xs:complexType>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            <xs:complexType>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
 </xs:schema>

=== pablogalvezprojectosdaw/XMLRepo/clientes/clientes_xsd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>



<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clientesSchema.xsd">
    <sede codigo = "Q78945612">
        <empleado>Manolo Hinojo</empleado>
        <fecha>14/11/2019</fecha>
        <descripcion>solvente</descripcion>
        <cliente codigo = "AAA-111">
            <direccion>C/Vapabajo nº 11</direccion>
            <numeroviviendas>2</numeroviviendas>
            <coste>5000</coste>
            <resumen>"Inserte descripción"</resumen>
            <plazo>20/06/2020</plazo>
        </cliente>
    </sede>
    <sede codigo ="K34565432">
        <direccion>C/Empinao nº 5</direccion>
        <empleado>Juan Gómez</empleado>
        <fecha>20/04/2018</fecha>
        <descripcion>insolvente</descripcion>
        <cliente codigo = "ABC-431">
            <numeroviviendas>1</numeroviviendas>
            <coste>3000</coste>
            <resumen>"Inserte descripción"</resumen>
            <plazo>14/3/2020</plazo>
        </cliente>
    </sede>
</clientes>
