<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Concesionario [
<!ELEMENT Concesionario (coche*)>
<!ELEMENT coche (codigo, marca, modelo, matricula, potencia, plazas,
numPuertas )>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numPuertas (#PCDATA)>
]>
<Concesionario>
<coche>
    <codigo>1</codigo>
    <marca>SEAT</marca>
    <modelo>Leon</modelo>
    <matricula>1234-BBB</matricula>
    <potencia>130</potencia>
    <plazas>5</plazas>
    <numPuertas>5</numPuertas>
</coche>
<coche>
    <codigo>2</codigo>
    <marca>BMW</marca>
    <modelo>Serie 1</modelo>
    <matricula>5678-CCC</matricula>
    <potencia>150</potencia>
    <plazas>4</plazas>
    <numPuertas>3</numPuertas>
</coche>
<coche>
<codigo>3</codigo>
<marca>Peugeot</marca>
<modelo>406</modelo>
<matricula>9067-DYC</matricula>
<potencia>90</potencia>
<plazas>5</plazas>
<numPuertas>4</numPuertas>
</coche>
</Concesionario>